### ISSUE TITLE
Error when uninstalling ActiveRecord::IrriversibleMigration in FixKanbanpaneWiplimitType

### ISSUE THREAD

**Issue by Garepjotr** [samchen2009/ekanban#17]
I get this when i do:
# rake redmine:plugins:migrate NAME=ekanban VERSION=0 RAILS_ENV=production

ActiveRecord::IrreversibleMigration/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:42:in `inverse'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:40:in`map'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:40:in `inverse'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:401:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:358:in `revert'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:400:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:399:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in`with_connection'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in`**send**'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `call'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in`ddl_transaction'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in`each'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:574:in`down'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:555:in `migrate'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in `execute'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:184:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:73:in `run'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'

**Comment by razor-rs** [comment]
same here.

**Comment by ppoektos** [comment]
Also can't uninstall:

```
# rake redmine:plugins:migrate NAME=ekanban VERSION=0 RAILS_ENV=production
Migrating ekanban (Ekanban Plugin)...
==  RenameKanbanCardJournalCol: reverting =====================================
-- rename_column("kanban_card_journals", :created_at, :created_on)
   -> 0.0139s
-- rename_column("kanban_card_journals", :kanban_card_id, :card_id)
   -> 0.0055s
==  RenameKanbanCardJournalCol: reverted (0.0195s) ============================

==  RenameKanbanCardJournalDetailsCol: reverting ==============================
-- rename_column("kanban_card_journal_details", :prop_key, :prop_keys)
   -> 0.0062s
==  RenameKanbanCardJournalDetailsCol: reverted (0.0063s) =====================

==  CreateKanbanCardJournalDetails: reverting =================================
-- drop_table("kanban_card_journal_details")
   -> 0.0008s
==  CreateKanbanCardJournalDetails: reverted (0.0009s) ========================

==  CreateKanbanCardJournals: reverting =======================================
-- drop_table("kanban_card_journals")
   -> 0.0007s
==  CreateKanbanCardJournals: reverted (0.0008s) ==============================

==  AddDescriptionToKanbanStage: reverting ====================================
-- remove_column("kanban_stages", :description)
   -> 0.0045s
==  AddDescriptionToKanbanStage: reverted (0.0045s) ===========================

==  AddDescriptionToKanbanState: reverting ====================================
-- remove_column("kanban_states", :description)
   -> 0.0043s
==  AddDescriptionToKanbanState: reverted (0.0043s) ===========================

==  AddKanbanIdToWorkflow: reverting ==========================================
-- remove_column("kanban_workflows", :kanban_id)
   -> 0.0043s
==  AddKanbanIdToWorkflow: reverted (0.0043s) =================================

==  AddPositionToKanbanPanes: reverting =======================================
-- remove_column("kanban_panes", :position)
   -> 0.0046s
==  AddPositionToKanbanPanes: reverted (0.0047s) ==============================

==  RenameKanbanCardCol: reverting ============================================
-- rename_column("kanban_cards", :verifier_id, :tester_id)
   -> 0.0056s
==  RenameKanbanCardCol: reverted (0.0057s) ===================================

==  AddInProgressColToKanbanPane: reverting ===================================
-- remove_column("kanban_panes", :in_progress)
   -> 0.0043s
==  AddInProgressColToKanbanPane: reverted (0.0044s) ==========================

==  AddRoleColToKanbanPane: reverting =========================================
-- remove_column("kanban_panes", :role_id)
   -> 0.0049s
==  AddRoleColToKanbanPane: reverted (0.0050s) ================================

==  AddStageToKanbanState: reverting ==========================================
-- remove_column("kanban_states", :stage_id)
   -> 0.0045s
==  AddStageToKanbanState: reverted (0.0046s) =================================

==  CreateKanbanStages: reverting =============================================
-- drop_table("kanban_stages")
   -> 0.0010s
==  CreateKanbanStages: reverted (0.0011s) ====================================

==  FixKanbanpaneWiplimitType: reverting ======================================
rake aborted!
An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:42:in `block in inverse'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:40:in `map'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration/command_recorder.rb:40:in `inverse'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:401:in `block (3 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:358:in `revert'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:400:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:399:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:574:in `down'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.13/lib/active_record/migration.rb:555:in `migrate'
/var/www/rm2.3.0/lib/redmine/plugin.rb:453:in `migrate_plugin'
/var/www/rm2.3.0/lib/redmine/plugin.rb:425:in `migrate'
/var/www/rm2.3.0/lib/redmine/plugin.rb:436:in `migrate'
/var/www/rm2.3.0/lib/tasks/redmine.rake:74:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by prmartinuk** [comment]
The change_column method in FixKanbanpaneWiplimitType (in 013_fix_kanbanpane_wiplimit_type.rb) doesn't automatically revert when migrating (change_column doesn't say what the column was previously). It needs the change method definition replaced by separate up and down methods to say how to do the migration.

I think a few of the other migrations need changing as well.

**Comment by fk0** [comment]
Facing this as well. Tried uninstall after spotting this bug https://github.com/samchen2009/ekanban/issues/12.
here are versions info

```
RAILS_ENV=production; ruby script/about
Invalid gemspec in [/usr/share/rubygems-integration/1.9.1/specifications/actionpack-3.2.13.gemspec]: Illformed requirement ["~> #<Gem::Version:0x8071f68>"]
Invalid gemspec in [/usr/share/rubygems-integration/1.9.1/specifications/actionpack-3.2.13.gemspec]: Illformed requirement ["~> #<Gem::Version:0x8071f68>"]

Environment:
  Redmine version                2.3.2.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               MySQL
Redmine plugins:
  ekanban                        0.0.1
```
