### ISSUE TITLE
Install fails on TurnkeyLinux Redmine appliance

### ISSUE THREAD

**Issue by vossenjp** [samchen2009/ekanban#36]
Environment:
    Redmine version                          2.2.3.stable
    Ruby version                             1.8.7 (x86_64-linux)
    Rails version                            3.2.12
    Environment                              production
    Database adapter                         MySQL
Redmine plugins:
    no plugin installed

Steps to reproduce:
- Fire up a TKL Redmine Appliance http://www.turnkeylinux.org/redmine
- Allow updates and reboot
- `gem install haml` --or-- `gem install haml -v "3.1.8"` (per https://github.com/samchen2009/ekanban/issues/6#issuecomment-21714425) 
- `rake redmine:plugins:migrate`  # THIS WORKS!
- Log in to web GUI = All "Administration" links work, no 404!
- `cd /var/www/redmine/plugins`
- `git clone git://github.com/samchen2009/ekanban`
- `bundle install`
- `rake redmine:plugins:migrate`  # Now FAILS with:
  
  (in /var/www/redmine)
  rake aborted!
  Mysql::Error: Table 'redmine_development.users' doesn't exist: SHOW FULL FIELDS FROM `users`
  /var/www/redmine/app/models/group.rb:32
  /var/www/redmine/plugins/ekanban/init.rb:51:in `_callback_before_5'
  /var/www/redmine/config/environment.rb:14
  Tasks: TOP => redmine:plugins:migrate => environment
  (See full trace by running task with --trace)

After a reboot and `Add a field "WIP limit" (format:integer) in 'Administrator' -> 'Custom fields' -> 'User'`:

Environment:
    Redmine version                          2.2.3.stable
    Ruby version                             1.8.7 (x86_64-linux)
    Rails version                            3.2.12
    Environment                              production
    Database adapter                         MySQL
Redmine plugins:
   ekanban                                  0.0.1

The "Administration > Kanban States" link is 404, which is much better than my first try when most admin links got broken.

I know https://github.com/samchen2009/ekanban says "this plugins only work (at least, only verified) on Redmine 2.1.x." yet http://www.redmine.org/plugins/ekanban says "0.11 (2013-03-09) Compatible with Redmine 2.2.x, 2.1.x. Fix some issues and verified it on 2.2.3."  Yet I'm seeing "ekanban 0.0.1" from my git clone.  What the heck?!?  

I've had no luck in Google or the issue tracker in figuring this out.  And I know nothing about Ruby, so I'll need newbie instructions for t-shooting Roby-related stuff.

---

/var/www/redmine/log/production.log when getting 404:

```
Started GET "/kanban_states/setup" for 192.168.99.185 at Sat Aug 17 20:31:25 +0000 2013
Processing by KanbanStatesController#setup as HTML
    Current user: admin (id=1)
Missing template, responding with 404
    Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 18ms (Views: 11.7ms | ActiveRecord: 0.3ms)
```

---

Full trace of rake failure:

```
# rake redmine:plugins:migrate --trace
(in /var/www/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Mysql::Error: Table 'redmine_development.users' doesn't exist: SHOW FULL FIELDS FROM \`users\`
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in \`query'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in \`execute'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in \`log'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in \`instrument'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in \`log'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in \`execute'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql_adapter.rb:324:in \`execute_and_free'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:424:in \`columns'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/schema_cache.rb:12:in \`initialize'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in \`call'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in \`default'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in \`[]'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in \`columns'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:237:in \`columns_hash'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/inheritance.rb:19:in \`descends_from_active_record?'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/inheritance.rb:25:in \`finder_needs_type_condition?'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/base.rb:455:in \`relation'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/scoping/named.rb:37:in \`scoped'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/querying.rb:9:in \`order'
/var/www/redmine/app/models/group.rb:32
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in \`load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in \`load_file'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:639:in \`new_constants_in'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:468:in \`load_file'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:353:in \`require_or_load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:502:in \`load_missing_constant'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:192:in \`const_missing'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:190:in \`each'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:190:in \`const_missing'
/var/www/redmine/plugins/ekanban/init.rb:51:in \`_callback_before_5'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:429:in \`_run__27736496__prepare__4__callbacks'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in \`send'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in \`__run_callback'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in \`_run_prepare_callbacks'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in \`send'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in \`run_callbacks'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:74:in \`prepare!'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:48:in \`prepare!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application/finisher.rb:47
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in \`instance_exec'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in \`run'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:55:in \`run_initializers'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in \`each'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in \`run_initializers'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:136:in \`initialize!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in \`send'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in \`method_missing'
/var/www/redmine/config/environment.rb:14
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:103:in \`require'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:103:in \`require_environment!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:297:in \`initialize_tasks'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in \`call'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in \`execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in \`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in \`execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:184:in \`invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in \`synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in \`invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:205:in \`invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:203:in \`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:203:in \`invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:183:in \`invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in \`synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in \`invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:170:in \`invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:143:in \`invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in \`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in \`each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in \`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:110:in \`run_with_threads'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:95:in \`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:73:in \`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in \`standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in \`run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/bin/rake:33
/usr/local/bin/rake:19:in \`load'
/usr/local/bin/rake:19
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by samchen2009** [comment]
"Missing template, responding with 404" means haml was not recognized, could you try to add "gem haml" into the Gemfile and bundle install again?

**Comment by vossenjp** [comment]
haml was listed in `gem list` but not in the `/var/www/redmine/Gemfile` file.  I fixed that, if I did it right, but that did not help.  (Remember, I know nothing about Ruby):

`vi /var/www/redmine/Gemfile`

```
root@redmine www/redmine# grep 'haml' /var/www/redmine/Gemfile
gem 'haml'
root@redmine www/redmine# gem list | grep haml
haml (3.1.8)
root@redmine www/redmine# bundle install
Resolving dependencies...
Using rake (10.0.4) 
Using i18n (0.6.4) 
[...]
Using fastercsv (1.5.5) 
Using haml (3.1.8) 
Using rack-ssl (1.3.3) 
[...]
Using yard (0.8.6.1) 
Your bundle is complete!
Gems in the groups rmagick and install were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

But it still fails:

```
404
The page you were trying to access doesn't exist or has been removed.
Back
```

Then it got worse after `/etc/init.d/apache2 restart`

```
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.
```

and `tail -F log/production.log` now gives

```
Started GET "/kanban_states/setup" for 192.168.99.185 at Thu Aug 22 05:28:51 +0000 2013
Processing by KanbanStatesController#setup as HTML
  Current user: admin (id=1)
  Rendered plugins/ekanban/app/views/kanban_states/_state_list.html.haml (2.2ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (4.1ms)
  Rendered plugins/ekanban/app/views/kanban_states/index.html.haml within layouts/base (4.5ms)
Completed 500 Internal Server Error in 10ms
ActionView::Template::Error (Mysql::Error: Table 'redmine_production.kanban_states' doesn't exist: SHOW FULL FIELDS FROM `kanban_states`):
    3: - trackers = Tracker.all
    4: - trackers.each do |t|
    5:   %h3= "Tracker #{t.name}"
    6:   - states = KanbanState.find_all_by_tracker_id(t.id)
    7:   - if !states.nil?
    8:     %table{:id => "kanban_state_#{t.id}",:class => "list"}
    9:       %thead
  activerecord (3.2.12) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
  activerecord (3.2.12) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
[... and lots more]
```

**Comment by samchen2009** [comment]
Error (Mysql::Error: Table 'redmine_production.kanban_states' doesn't exist: SHOW FULL FIELDS FROM `kanban_states`) showed that your database was not migrated properly, which should be done by 'rake redmine:plugins:migrate'. Could you try this command again and show me the output log?

**Comment by vossenjp** [comment]
STILL fails as noted in my original message at top!

```
root@redmine www/redmine# rake redmine:plugins:migrate
rake aborted!
Mysql::Error: Table 'redmine_development.users' doesn't exist: SHOW FULL FIELDS FROM `users`
/var/www/redmine/app/models/group.rb:32
/var/www/redmine/plugins/ekanban/init.rb:51:in `_callback_before_5'
/var/www/redmine/config/environment.rb:14
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

See also "Full trace of rake failure:" at top...

**Comment by samchen2009** [comment]
'users' is a table of redmine, not ekanban, it should be there so I think this is something to do with the mysql, I found a topic in stackoverflow, http://stackoverflow.com/questions/7759170/mysql-table-doesnt-exist-but-it-does-or-it-should, which looks similar and may be helpful. You could  login to Mysql and try 'select \* from users', If it also show s the 'not exist' error, you can follow the suggest in that post.

**Comment by vossenjp** [comment]
This is an ekanban problem, because `rake` WORKS until I install the ekanban plugin, then `rake` fails!  Please re-read my original post, especially the "Steps to reproduce" which a) show this problem and b) tells you how to reproduce it.  It was worked the same way twice, by creating a fresh VM though admittedly starting from the same TKL Redmine Appliance http://www.turnkeylinux.org/redmine both times).

**Comment by prmartinuk** [comment]
Try running the command "rake redmine:plugins:migrate RAILS_ENV=production"
(or change production to whatever Rails environment you are using).

If you don't specify the Rails environment then it will use the default environment, which is rarely the one you really want to use. I think in your case the default Rails environment (which is probably Development) doesn't have Redmine set up on it.

The documentation probably should be changed to use the command that Redmine recommends for installing and migrating plugins.

**Comment by vossenjp** [comment]
Looks like that worked!  Note, I was working from the "INSTALLATION INSTRUCTIONS" docs at https://github.com/samchen2009/ekanban, so that might be a good place to update.  I'm also not clear why I did not see the issue until I installed ekanban, but I suspect that lack of understanding is due to my complete cluelessness about Ruby.

Thanks for the help!

From completeness:

```
root@redmine www/redmine# rake redmine:plugins:migrate RAILS_ENV=production
Migrating ekanban (Ekanban Plugin)...
==  CreateKanbans: migrating ================================================
-- create_table(:kanbans)
   -> 0.0625s
==  CreateKanbans: migrated (0.0626s) =======================================

==  CreateKanbanStates: migrating ===========================================
-- create_table(:kanban_states)
   -> 0.0122s
==  CreateKanbanStates: migrated (0.0123s) ==================================

==  CreateKanbanPanes: migrating ============================================
-- create_table(:kanban_panes)
   -> 0.0049s
==  CreateKanbanPanes: migrated (0.0050s) ===================================

==  CreateIssueStatusKanbanStates: migrating ================================
-- create_table(:issue_status_kanban_states)
   -> 0.0019s
==  CreateIssueStatusKanbanStates: migrated (0.0020s) =======================

==  CreateKanbanCards: migrating ============================================
-- create_table(:kanban_cards)
   -> 0.0053s
==  CreateKanbanCards: migrated (0.0053s) ===================================

==  CreateKanbanWorkflows: migrating ========================================
-- create_table(:kanban_workflows)
   -> 0.0020s
==  CreateKanbanWorkflows: migrated (0.0020s) ===============================

==  ChangeKanbanPanes: migrating ============================================
-- change_table(:kanban_panes)
   -> 0.0351s
==  ChangeKanbanPanes: migrated (0.0352s) ===================================

==  ChangeKanbanCards: migrating ============================================
-- change_table(:kanban_cards)
   -> 0.0053s
==  ChangeKanbanCards: migrated (0.0054s) ===================================

==  AddKanbanTablesOptions: migrating =======================================
-- change_column(:kanbans, :name, :string, {:null=>false, :limit=>32})
   -> 0.0057s
-- change_column(:kanbans, :project_id, :integer, {:null=>false})
   -> 0.0046s
-- change_column(:kanbans, :tracker_id, :integer, {:null=>false})
   -> 0.0039s
-- change_column(:kanbans, :is_valid, :boolean, {:default=>true})
   -> 0.0019s
-- add_column(:kanbans, :description, :text, {:limit=>256})
   -> 0.0031s
-- change_column(:kanban_states, :name, :string, {:null=>false, :limit=>32})
   -> 0.0057s
-- change_column(:kanban_states, :is_default, :boolean, {:default=>false})
   -> 0.0019s
-- change_column(:kanban_states, :is_initial, :boolean, {:default=>false})
   -> 0.0076s
-- change_column(:kanban_states, :is_closed, :boolean, {:default=>false})
   -> 0.0020s
-- change_column(:kanban_panes, :name, :string, {:limit=>32})
   -> 0.0048s
-- add_column(:kanban_panes, :description, :text, {:limit=>256})
   -> 0.0073s
-- change_column(:kanban_panes, :wip_limit_auto, :boolean, {:default=>true})
   -> 0.0021s
-- change_column(:kanban_panes, :wip_limit, :boolean, {:default=>1, :null=>false})
   -> 0.0061s
-- change_column(:kanban_panes, :kanban_id, :integer, {:null=>false})
   -> 0.0077s
-- change_column(:kanban_workflows, :check_role, :boolean, {:default=>false})
   -> 0.0019s
-- change_column(:kanban_workflows, :check_wip_limit, :boolean, {:default=>true})
   -> 0.0060s
==  AddKanbanTablesOptions: migrated (0.0734s) ==============================

==  FixKanbanpaneWiplimitType: migrating ====================================
-- change_column(:kanban_panes, :wip_limit, :integer, {:default=>1, :null=>false})
   -> 0.0061s
==  FixKanbanpaneWiplimitType: migrated (0.0062s) ===========================

==  CreateKanbanStages: migrating ===========================================
-- create_table(:kanban_stages)
   -> 0.0018s
==  CreateKanbanStages: migrated (0.0019s) ==================================

==  AddStageToKanbanState: migrating ========================================
-- add_column(:kanban_states, :stage_id, :integer, {:default=>0})
   -> 0.0052s
==  AddStageToKanbanState: migrated (0.0053s) ===============================

==  AddRoleColToKanbanPane: migrating =======================================
-- add_column(:kanban_panes, :role_id, :integer, {:default=>1, :null=>false})
   -> 0.0224s
==  AddRoleColToKanbanPane: migrated (0.0225s) ==============================

==  AddInProgressColToKanbanPane: migrating =================================
-- add_column(:kanban_panes, :in_progress, :boolean, {:default=>true, :null=>false})
   -> 0.0053s
==  AddInProgressColToKanbanPane: migrated (0.0055s) ========================

==  RenameKanbanCardCol: migrating ==========================================
-- rename_column(:kanban_cards, :tester_id, :verifier_id)
   -> 0.0045s
==  RenameKanbanCardCol: migrated (0.0046s) =================================

==  AddPositionToKanbanPanes: migrating =====================================
-- add_column(:kanban_panes, :position, :integer, {:default=>1})
   -> 0.0033s
==  AddPositionToKanbanPanes: migrated (0.0033s) ============================

==  AddKanbanIdToWorkflow: migrating ========================================
-- add_column(:kanban_workflows, :kanban_id, :integer, {:default=>0})
   -> 0.0036s
==  AddKanbanIdToWorkflow: migrated (0.0037s) ===============================

==  AddDescriptionToKanbanState: migrating ==================================
-- add_column(:kanban_states, :description, :text, {:limit=>128})
   -> 0.0069s
==  AddDescriptionToKanbanState: migrated (0.0070s) =========================

==  AddDescriptionToKanbanStage: migrating ==================================
-- add_column(:kanban_stages, :description, :text, {:limit=>128})
   -> 0.0059s
==  AddDescriptionToKanbanStage: migrated (0.0060s) =========================

==  CreateKanbanCardJournals: migrating =====================================
-- create_table(:kanban_card_journals)
   -> 0.0039s
==  CreateKanbanCardJournals: migrated (0.0040s) ============================

==  CreateKanbanCardJournalDetails: migrating ===============================
-- create_table(:kanban_card_journal_details)
   -> 0.0019s
==  CreateKanbanCardJournalDetails: migrated (0.0020s) ======================

==  RenameKanbanCardJournalDetailsCol: migrating ============================
-- rename_column(:kanban_card_journal_details, :prop_keys, :prop_key)
   -> 0.0066s
==  RenameKanbanCardJournalDetailsCol: migrated (0.0066s) ===================

==  RenameKanbanCardJournalCol: migrating ===================================
-- rename_column(:kanban_card_journals, :card_id, :kanban_card_id)
   -> 0.0056s
-- rename_column(:kanban_card_journals, :created_on, :created_at)
   -> 0.0077s
==  RenameKanbanCardJournalCol: migrated (0.0134s) ==========================
```
