### ISSUE TITLE
No route matches

### ISSUE THREAD

**Issue by pavo976** [samchen2009/ekanban#44]
Greetings.

redmine: 2.3.1

gem list
**\* LOCAL GEMS ***
haml (4.0.3)
json (1.8.0)
rdoc (4.0.1)
simpleconsole (0.1.1)
task (0.0.1)
tilt (1.4.1)

ruby-rails-3.2   3.2.13-2~precise+2
ruby-railties-3.2        3.2.13-4~precise+2

Can you please tell how to solve this problem? :

ActionController::RoutingError (No route matches {:action=>"setup", :controller=>"kanban_states"}):
  lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
  lib/redmine/menu_manager.rb:102:in`render_menu_node'
  lib/redmine/menu_manager.rb:91:in `render_menu'
  lib/redmine/menu_manager.rb:168:in`menu_items_for'
  lib/redmine/menu_manager.rb:165:in `each'
  lib/redmine/menu_manager.rb:165:in`menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  app/views/admin/_menu.html.erb:2:in`_app_views_admin__menu_html_erb__205109753_70356591697980'
  app/views/admin/index.html.erb:5:in `_app_views_admin_index_html_erb___377077887_70356593778020'

**Comment by pavo976** [comment]
Do not use this guide:
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_Ubuntu_step_by_step

This manual has not caused any problems with the installation of a very redmine, and the installation of the module.
Thanks.
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_231_On_Ubuntu_1204_with_git_and_Redmine_Git_Hosting_plugin
