### ISSUE TITLE
The plugin breaks the admin interface on Redmin 2.4

### ISSUE THREAD

**Issue by ronlinet** [samchen2009/ekanban#85]
Hi guys, 

I am running Redmine2.4 installed vie apt-get package on Ubuntu server 14.04. The installation worked as required till I have installed ekanban .  

Now I  am getting “Page not found” error every time when I try to access the admin interface => http:redmine-server/admin  => “Page not found The page you were trying to access doesn't exist or has been removed.”

All other interfaces work as required only the admin interface is broken.

**Comment by prmartinuk** [comment]
Do you get any more detail in the log files?

**Comment by ronlinet** [comment]
Thx for having look at my issue. 
I solved the problem by completly removing the plugin with all its dependancy.

Remove the plugin;
rake redmine:plugins:migrate NAME=plugin-name VERSION=0 RAILS_ENV=production

Uninstall dependency:
gem uninstall haml 

Clean up the plugin folder:
rm -R /path/to/plugin-name

**Comment by prmartinuk** [comment]
That definitely narrows it down to a problem with this plugin.

I am not a Ruby/Rails developer so I could be completely wrong but the only way I can the Redmine admin page to give a page not found error (404) is if the routing is missing. The only change to the admin page that the plugin makes is adding a menu item to it and Rails uses the routing to make the URL for the menu item.
Quite why the routing was missing I'm not sure. The only thing I can think was that the config/routes.rb file was missing or corrupted.

**Comment by ronlinet** [comment]
Thank you for your contribution prmartinuk .

I have checked the issue queue and I noticed that some users were able to fix similar problem with downgrading haml to 3.1.8. I have downgraded my haml from 4 to 3.1.8 but it didn't fix the issue and the plugin is still knocking out the admin  page. 

I have checked the logs and your conclusion about the router is correct. 
The router file is right in config/routes.rb but I think that the installation process incorrectly override the code. I would welcome if some community member drop a code snipet to hack the config/routes.rb. 

The error logs:
App 30874 stderr: ActionController::RoutingError (No route matches {:controller=>"kanban_states", :action=>"setup"}):
App 30874 stderr:   lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
App 30874 stderr:   lib/redmine/menu_manager.rb:102:in`render_menu_node'
App 30874 stderr:   lib/redmine/menu_manager.rb:91:in `block in render_menu'
App 30874 stderr:   lib/redmine/menu_manager.rb:168:in`block in menu_items_for'
App 30874 stderr:   lib/redmine/menu_manager.rb:165:in `each'
App 30874 stderr:   lib/redmine/menu_manager.rb:165:in`menu_items_for'
App 30874 stderr:   lib/redmine/menu_manager.rb:90:in `render_menu'
App 30874 stderr:   app/views/admin/_menu.html.erb:2:in`_app_views_admin__menu_html_erb___4035781756835632397_36090680'
App 30874 stderr:   app/views/admin/index.html.erb:5:in `_app_views_admin_index_html_erb__3659061063313912048_60910980'

**Comment by prmartinuk** [comment]
Do you have any other plugins installed which have routings, and do they work?
There are a couple of issues in Redmine's issues page (http://www.redmine.org/issues/12590 and http://www.redmine.org/issues/16226) where people are reporting that Redmine is not finding the routes.rb files for the plugins, with one saying it is fixed in Ruby. However, both of these are for Windows rather than Ubuntu.
